[package]
name="wsrelay"
version.workspace=true
edition.workspace=true
license.workspace=true
repository.workspace=true

[[bin]]
name="wgw-bridge"
path="src/main.rs"

[dependencies]
tokio.workspace=true
anyhow.workspace=true
clap.workspace=true
tracing.workspace=true
tracing-subscriber.workspace=true
futures-util.workspace=true
tokio-tungstenite.workspace=true
tokio-rustls.workspace=true
rustls.workspace=true
rustls-pemfile.workspace=true

[dev-dependencies]
rcgen.workspace=true
