[package]
name="server"
version.workspace=true
edition.workspace=true
license.workspace=true
repository.workspace=true

[lib]
name="server"
path="src/lib.rs"

[[bin]]
name="wgw-server"
path="src/main.rs"

[dependencies]
wgcore={path="../wgcore"}
wsrelay={path="../wsrelay"}
tokio.workspace=true
anyhow.workspace=true
serde.workspace=true
serde_json.workspace=true
clap.workspace=true
tracing.workspace=true
tracing-subscriber.workspace=true
ipstack.workspace=true
tokio-socks.workspace=true
ipnet.workspace=true
etherparse.workspace=true

[dev-dependencies]
boringtun.workspace=true
