[package]
name="wgclient"
version.workspace=true
edition.workspace=true
license.workspace=true
repository.workspace=true

[dependencies]
wgcore={path="../wgcore"}
wsrelay={path="../wsrelay"}
tokio.workspace=true
anyhow.workspace=true
tracing.workspace=true
ipnet={workspace=true}

[target.'cfg(windows)'.dependencies]
wintun-bindings.workspace=true

[dev-dependencies]
tracing-subscriber.workspace=true
server={path="../server"}
etherparse.workspace=true
serde_json.workspace=true
